const con5Data = [
    {
        id: 1,
        title: '봉인전기',
        device: 'Nintendo Switch 2',
        date: '2025. 12월 예정',
        copyright: '한국닌텐도',
        ver1: '패키지 버전',
        ver2: '다운로드 버전',
        imgUrl: '/images/6.jpg',
    },
    {
        id: 2,
        title: '드래그 앤드 드라이브',
        device: 'Nintendo Switch 2',
        date: '2025.8.14 예정',
        copyright: '한국닌텐도',
        ver1: '패키지 버전',
        ver2: '다운로드 버전',
        imgUrl: '/images/7.jpg',
    },
    {
        id: 3,
        title: '동키콩 바난자',
        device: 'Nintendo Switch 2',
        date: '2025.7.17',
        copyright: '한국닌텐도',
        ver1: '패키지 버전',
        ver2: '다운로드 버전',
        imgUrl: '/images/8.jpg',
    },
    {
        id: 4,
        title: 'Minecraft',
        device: 'Nintendo Switch 2',
        date: '2025.6.5',
        copyright: '한국닌텐도',
        ver1: '패키지 버전',
        ver2: '다운로드 버전',
        imgUrl: '/images/9.jpg',
    },
    {
        id: 5,
        title: '마리오 카트 월드',
        device: 'Nintendo Switch 2',
        date: '2025.6.5',
        copyright: '한국닌텐도',
        ver1: '패키지 버전',
        ver2: '다운로드 버전',
        imgUrl: '/images/11.jpg',
    },
    {
        id: 6,
        title: '웰컴투어',
        device: 'Nintendo Switch 2',
        date: '2025.6.5',
        copyright: '한국닌텐도',
        ver1: '패키지 버전',
        ver2: '다운로드 버전',
        imgUrl: '/images/10.jpg',
    },
];

export default con5Data;
